sequenceDiagram
  participant participant_createChess as createChess
  participant participant_readChessPieces as readChessPieces
  participant_readChessPieces->>participant_createChess: createChess()
  participant_createChess-->>participant_readChessPieces: return
